-- MySQL Script generated by MySQL Workbench
-- Fri May 31 02:33:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CVUBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CVUBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CVUBD` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `CVUBD` ;

-- -----------------------------------------------------
-- Table `CVUBD`.`tblSeccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CVUBD`.`tblSeccion` (
  `idSeccion` VARCHAR(6) NOT NULL,
  `trayecto` INT NOT NULL,
  PRIMARY KEY (`idSeccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CVUBD`.`tblEleccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CVUBD`.`tblEleccion` (
  `codigo` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `estado` INT(1) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CVUBD`.`tblCandidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CVUBD`.`tblCandidato` (
  `codigo` VARCHAR(10) NOT NULL,
  `cedula` VARCHAR(8) NOT NULL,
  `seccion` VARCHAR(6) NOT NULL,
  `eleccion` VARCHAR(10) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `FK_candidatoSeccion_idx` (`seccion` ASC),
  INDEX `FK_candidatoCampaña_idx` (`eleccion` ASC),
  CONSTRAINT `FK_candidatoSeccion`
    FOREIGN KEY (`seccion`)
    REFERENCES `CVUBD`.`tblSeccion` (`idSeccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_candidatoCampaña`
    FOREIGN KEY (`eleccion`)
    REFERENCES `CVUBD`.`tblEleccion` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CVUBD`.`tblEstudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CVUBD`.`tblEstudiante` (
  `cedula` VARCHAR(8) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `rol` INT(1) NOT NULL,
  PRIMARY KEY (`cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CVUBD`.`tblVotaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CVUBD`.`tblVotaciones` (
  `codigo` VARCHAR(8) NOT NULL,
  `idVotante` VARCHAR(10) NOT NULL,
  `idElegido` VARCHAR(10) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `FK_votacionesEstudiante_idx` (`idVotante` ASC),
  INDEX `FK_votacionesCandidato_idx` (`idElegido` ASC),
  CONSTRAINT `FK_votacionesEstudiante`
    FOREIGN KEY (`idVotante`)
    REFERENCES `CVUBD`.`tblEstudiante` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_votacionesCandidato`
    FOREIGN KEY (`idElegido`)
    REFERENCES `CVUBD`.`tblCandidato` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
